const String CART_TABLE_NAME = "Cart";
const String CART_FIELD_ID = "id";
const String CART_FIELD_PRODUCT_ID = "product_id";
const String CART_FIELD_NAME = "name";
const String CART_FIELD_IMAGE = "image";
const String CART_FIELD_PRICE = "price";
const String CART_FIELD_QUANTITY = "quantity";
const String CART_FIELD_SIZE = "size";
const String CART_FIELD_COLOR = "color";

const String CREATE_CART_TABLE_QUERY = ''' 
 CREATE TABLE $CART_TABLE_NAME(
 $CART_FIELD_ID INTEGER PRIMARY KEY AUTOINCREMENT,
 $CART_FIELD_PRODUCT_ID TEXT NOT NULL,
 $CART_FIELD_NAME TEXT NOT NULL,
 $CART_FIELD_IMAGE TEXT NOT NULL,
 $CART_FIELD_PRICE DOUBLE NOT NULL,
 $CART_FIELD_QUANTITY INTEGER NOT NULL,
 $CART_FIELD_SIZE TEXT NOT NULL,
 $CART_FIELD_COLOR TEXT NOT NULL
 );
 ''';

